name: default

on: push

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.13"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
  setup-test-env:
    runs-on: ubuntu-latest
    name: create test environment
    steps:
      - name: create container
        id: create
        uses: Scalr/gh-action-revizor@feature/SCALRCORE-16917
        with:
          command: "create"
        env: &env
          REVIZOR_TOKEN: ${{ secrets.REVIZOR_TOKEN }}
          SCALR_TOKEN: ${{ secrets.SCALR_TOKEN }}
  delete-test-env:
    runs-on: ubuntu-latest
    name: delete test environment
    steps:
      - name: delete container
        id: delete
        uses: Scalr/gh-action-revizor@feature/SCALRCORE-16917
        with:
          command: "delete"
          id: "be0bf69f48f9"
        env: *env
