name: default

on: push

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.13"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
  test:
    runs-on: ubuntu-latest
    name: tests
    env:
      REVIZOR_URL: ${{ secrets.REVIZOR_URL }}
      REVIZOR_TOKEN: ${{ secrets.REVIZOR_TOKEN }}
      SCALR_TOKEN: ${{ secrets.SCALR_TOKEN }}
    steps:
      - name: create container
        id: create
        uses: Scalr/gh-action-revizor@feature/SCALRCORE-16917
        with:
          command: create
      - name: acc tests
        env:
          SCALR_HOSTNAME: "scalr-id"
        run:  printenv
      - name: delete container
        id: delete
        if: ${{ always() }}
        uses: Scalr/gh-action-revizor@feature/SCALRCORE-16917
        with:
          command: delete
          id: ${{ steps.create.outputs.id }}
