name: default

on: push

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.13"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
  test:
    runs-on: ubuntu-latest
    name: tests
    env:
      REVIZOR_URL: ${{ secrets.REVIZOR_URL }}
      REVIZOR_TOKEN: ${{ secrets.REVIZOR_TOKEN }}
      SCALR_TOKEN: ${{ secrets.SCALR_TOKEN }}
    steps:
      - name: Create container
        id: create
        uses: Scalr/gh-action-revizor@feature/SCALRCORE-16917
        with:
          command: create error
      - name: Acceptance tests
        env:
          SCALR_HOSTNAME: ${{ steps.create.outputs.hostname }}
        run: |
          git clone https://github.com/Scalr/terraform-provider-scalr.git
          cd terraform-provider-scalr
          ls -l
      - name: Delete container
        id: delete
        if: ${{ always() }}
        # if: ${{  steps.create.outputs.container_id }}
        uses: Scalr/gh-action-revizor@feature/SCALRCORE-16917
        with:
          command: delete
          container_id: ${{ steps.create.outputs.container_id }}
